@startuml
actor "VIS operaator" as ac_vis
actor "EHS operaator" as ac_ehs
participant "VIS" as vis
participant "RR" as rr
participant "EHS" as ehs

activate vis
activate rr

ac_vis -> vis : Algata valimiste algnimekirja hankimine
vis -> rr : RRValimisteAlgNimekiriRequest
rr -> vis : RRValimisteAlgNimekiriResponse

...Luuakse EHS instants...

ac_ehs -> ehs: Algata valimissündmus
activate ehs
ac_vis -> vis: Ekspordi valimiste algnimekiri
vis -> ac_vis: Valimiste algnimekiri, 0
ac_vis -> ac_ehs: Valimiste algnimekiri, 0
ac_ehs -> ac_ehs: Allkirjasta valimiste algnimekiri, 0
ac_ehs -> ehs: Impordi valimiste algnimekiri, 0
ehs -> ehs: Impordi valimiste algnimekiri, 0

...Käivitatakse valimised...

ehs -> vis : Anna muudatused 1
vis -> ehs : Veel mitte. HTTP 204 - no-content

...mingi aja möödudes...

ehs -> vis : Anna muudatused 1
vis -> ehs : Valimiste muudatusnimekiri (ZIP content,sig), 1
ehs -> ehs : Impordi valimiste muudatusnimekiri, 1
ehs -> ac_ehs: Nimekiri 1, laadimisel probleem

...Probleem lahendatakse EHS poolel...

ehs -> vis : Anna muudatused 1
vis -> ehs : Valimiste muudatusnimekiri, 1
ehs -> ehs : Impordi valimiste muudatusnimekiri, 1

...Mõne aja möödudes...


ehs -> vis : Anna muudatused 2
vis -> ehs : Valimiste muudatusnimekiri, 2
ehs -> ehs : Impordi valimiste muudatusnimekiri, 2
ehs -> ac_ehs: Nimekiri 2, laadimisel probleem

...probleem lahendatakse  RR või VIS poolel, tekib nimekiri 3...

ac_ehs -> ehs: Allkirjastatud korraldus jätta vahele nimekiri 2

ehs -> vis : Anna muudatused 3
vis -> ehs : Valimiste muudatusnimekiri, 3
ehs -> ehs : Impordi valimiste muudatusnimekiri, 3

...

ehs -> ac_ehs: e-hääletanute nimekiri

deactivate vis
deactivate rr
deactivate ehs
@enduml
