@startuml
autonumber
actor "EHS operaator" as ac_ehs
participant "EHS" as ehs
participant "VIS" as vis
actor "VIS operaator" as ac_vis
participant "RR" as rr

activate vis
activate rr

ac_vis -> vis : Algata valijate algnimekirja hankimine
vis -> rr : RRValimisteAlgNimekiriRequest
rr -> vis : RRValimisteAlgNimekiriResponse

...Algnimekiri edastatakse EHS operaatorile...

ac_ehs -> vis: Ekspordi valijate algnimekiri
vis -> ac_ehs: Valijate algnimekiri 0

...EHS on valmis algnimekirja rakendama...

ac_ehs -> ac_ehs: Allkirjasta valijate algnimekiri 0
activate ehs
ac_ehs -> ehs: Impordi valijate algnimekiri 0
ehs -> ehs: Impordi valijate algnimekiri 0

...Algab elektrooniline hääletamine...
par Paralleelprotsessid
	loop Intervalliga X aja tagant
      vis -> rr : RRValimisteNimekirjaMuudatusedRequest
      rr -> vis : RRValimisteNimekirjaMuudatusedResponse
	end

	else

	ehs -> vis : Anna valijate nimekirja muudatused (1)
	vis -> ehs : Veel mitte. HTTP 404 - no-content

end

deactivate vis
deactivate rr
deactivate ehs

@enduml
